### PR TITLE
Updated zendesk_api_client_php to version 2

### PR DESCRIPTION
**Pull request by PieterScheffers**

### CODE REVIEW

**Comment by tom-huddle** [comment]
Thanks for contributing!

Could you explain why there was a need to change the Client to HTTPClient and token-based auth to basic auth?

**Comment by PieterScheffers** [comment]
No problem. I needed the incremental API of Zendesk, which is in version 2 of the API.

I followed the guide for upgrading to version 2.
[Upgrade guide](https://github.com/zendesk/zendesk_api_client_php/wiki/Upgrading-from-v1-to-v2)

**Comment by tom-huddle** [comment]
Great, thanks, I hadn't seen this article.

Could you squash the three commits 1637d6c, a4ed21d and c7c17ac into one commit? This just makes the history cleaner and means rolling back to any of those commits won't break the code.

Then I will test and merge.

**Comment by PieterScheffers** [comment]
Ok I squashed the three commits into one and learned something new;)

**Comment by tom-huddle** [comment]
Thanks, this has now been merged to master!

On Wednesday, 21 October 2015, Pieter Scheffers notifications@github.com
wrote:

> Ok I squashed the three commits into one and learned something new;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/huddledigital/zendesk-laravel/pull/1#issuecomment-149918438
> .

## 

_Tom Parson_
Director

http://workwithhuddle.com
_Huddle Digital_
workwithhuddle.com http://workwithhuddle.com0161 327 2827

This email is commercial in confidence.

**Pull request merged**
